#include "decode_buffer.c"
#include "encode_buffer.c"
#include "cc_ss_decoder.c"
#include "cc_ss_encoder.c"
#include "ipp_fdct.c"
#include "ipp_idct.c"
#include "huff_decode.c"
#include "huff_encode.c"
#include "frame_decoder.c"
#include "frame_encoder.c"
#include "fileio.c"
#include "init.c"
#include "jpgintfc.c"
#include "version.c"
#include "decoder_parser.c"
#include "encoder_parser.c"
#include "scan_decoder.c"
#include "scan_encoder.c"
#include "tables.c"



